# Generated by Django 4.1.8 on 2026-09-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name, e.g., developer_mode', max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم العربي')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('icon', models.CharField(default='fa-cube', help_text='FontAwesome class, e.g., fa-code', max_length=100)),
                ('icon_bg', models.CharField(default='bg-gray-900', help_text='Tailwind bg class', max_length=100)),
                ('icon_color', models.CharField(default='text-white', help_text='Tailwind text color', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف العربي')),
                ('category', models.CharField(blank=True, default='عام', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تطبيق',
                'verbose_name_plural': 'التطبيقات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('rml_path', models.CharField(blank=True, help_text='Path to .rml file', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
    ]
