# Generated by Django 4.1.8 on 2026-09-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='e.g., emp_report.rml or hr_form.fmlk', max_length=200, unique=True)),
                ('file_type', models.CharField(choices=[('rml', 'RML Report'), ('fml', 'FML Form'), ('fmlk', 'FMLK Form')], default='rml', max_length=10)),
                ('owner', models.CharField(blank=True, help_text='user:admin', max_length=100)),
                ('aces_json', models.JSONField(default=list, help_text='List of ACEs: [{principal, actions, effect}]')),
                ('inherit', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صلاحية ملف',
                'verbose_name_plural': 'صلاحيات الملفات',
            },
        ),
    ]
