# Generated by Django 4.1.8 on 2026-09-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urs', '0002_filepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_json', models.JSONField(default=dict, verbose_name='ملف التشغيل')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الملف')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('rml_count', models.IntegerField(default=0, verbose_name='عدد التقارير')),
                ('fml_count', models.IntegerField(default=0, verbose_name='عدد النماذج')),
                ('permissions_hash', models.CharField(blank=True, max_length=64, verbose_name='بصمة الصلاحيات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف تشغيل المستخدم',
                'verbose_name_plural': 'ملفات تشغيل المستخدمين',
            },
        ),
    ]
