# Generated by Django 4.1.8 on 2026-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0003_userdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='معرف الاتصال', max_length=100, unique=True, verbose_name='الاسم')),
                ('host', models.CharField(default='172.16.10.101', max_length=255, verbose_name='المضيف')),
                ('port', models.IntegerField(default=5432, verbose_name='المنفذ')),
                ('user', models.CharField(default='postgres', max_length=100, verbose_name='المستخدم')),
                ('password', models.CharField(default='postgres', max_length=255, verbose_name='كلمة المرور')),
                ('instance', models.CharField(blank=True, help_text='اسم قاعدة البيانات أو SID', max_length=100, verbose_name='المثيل')),
                ('engine', models.CharField(choices=[('oracle', 'Oracle'), ('sqlserver', 'SQL Server'), ('zk', 'ZK'), ('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], default='postgres', max_length=20, verbose_name='المحرك')),
                ('is_local', models.BooleanField(default=True, help_text='إذا True قابل للترحيل والتحديث وإلا للقراءة فقط', verbose_name='محلي')),
                ('schema', models.CharField(blank=True, help_text='Schema مثل HR_SYS', max_length=100, verbose_name='المخطط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اتصال',
                'verbose_name_plural': 'الاتصالات',
                'ordering': ['name'],
            },
        ),
    ]
