# Generated by Django 4.1.8 on 2026-09-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0004_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'المدن',
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SA, EG, AE', max_length=10, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='English Name')),
                ('phone_code', models.CharField(blank=True, max_length=10, verbose_name='مفتاح الاتصال')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SAR, USD, EGP', max_length=10, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='الرمز المختصر')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=18, verbose_name='السعر')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CMP, cmp1', max_length=30, unique=True, verbose_name='رمز الشركة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='الرقم الضريبي')),
                ('fiscal_year', models.IntegerField(default=2026, verbose_name='السنة المالية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urs.city', verbose_name='المدينة')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urs.country', verbose_name='الدولة')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urs.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='urs.country', verbose_name='الدولة'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'name')},
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='MAIN, RYD01', max_length=30, verbose_name='رمز الفرع')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('branch_type', models.CharField(choices=[('main', 'رئيسي'), ('sub', 'فرعي'), ('warehouse', 'مستودع'), ('pos', 'نقطة بيع')], default='main', max_length=20, verbose_name='النوع')),
                ('schema_name', models.CharField(blank=True, help_text='company_branch_year', max_length=100, verbose_name='السكима')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urs.city', verbose_name='المدينة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='urs.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['company__code', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
