# Generated by Django 4.1.8 on 2026-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0005_city_country_currency_company_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_check_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='بواسطة'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_check_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='نتيجة آخر فحص'),
        ),
    ]
