# Generated by Django 4.1.8 on 2026-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0006_connection_last_check_at_connection_last_check_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='filter', max_length=20, verbose_name='النوع')),
                ('app', models.CharField(max_length=100, verbose_name='التطبيق')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('filter', models.JSONField(default=list, verbose_name='الفلاتر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نموذج محفوظ',
                'verbose_name_plural': 'النماذج المحفوظة',
                'db_table': 'presets',
                'ordering': ['app', 'type', 'name'],
            },
        ),
    ]
