# Generated by Django 4.1.8 on 2026-09-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0011_connection_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='devices',
            field=models.TextField(blank=True, default='[]', help_text="JSON: أجهزة IoT إضافية بنفس الاتصال ['ip:port'] أو [{'host': 'ip', 'port': 4370}] — تُجلب مع الجهاز الرئيسي (UNION ALL)", verbose_name='أجهزة إضافية'),
        ),
        migrations.AlterField(
            model_name='iotmirror',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
