# Generated by Django 4.2.30 on 2026-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0012_alter_connection_devices_alter_iotmirror_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='instance_name',
            field=models.CharField(blank=True, default='', help_text='SQL Server فقط (مثال SQLEXPRESS) — يبني عنوان الخادم host\\instance', max_length=100, verbose_name='اسم مثيل SQL Server'),
        ),
    ]
