# Generated by Django 4.2.30 on 2026-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urs', '0014_connection_last_check_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='معرف السجل')),
                ('table_name', models.CharField(blank=True, default='', max_length=150, verbose_name='الجدول')),
                ('ad_machine', models.CharField(blank=True, default='', max_length=200, verbose_name='جهاز الإدخال')),
                ('edit_machine', models.CharField(blank=True, default='', max_length=200, verbose_name='جهاز التعديل')),
                ('print_count', models.IntegerField(default=0, verbose_name='عدد مرات الطباعة')),
                ('ad_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإضافة')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'سجل مراقبة',
                'verbose_name_plural': 'سجلات المراقبة',
                'ordering': ['-edit_date', '-ad_date'],
            },
        ),
    ]
