"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from urs import views as urs_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', urs_views.workspace_home, name='workspace'),
    path('apps/', urs_views.home, name='apps'),
    path('exit/', urs_views.workspace_exit, name='exit'),
    path('api/workspaces/', urs_views.api_workspaces_list, name='api_workspaces_list'),
    path('api/workspaces/<str:ws_id>/fiscal-years/', urs_views.api_workspace_fiscal_years, name='api_workspace_fiscal_years'),
    path('api/workspaces/<str:ws_id>/login/', urs_views.api_workspace_login, name='api_workspace_login'),
    path('api/workspaces/<str:ws_id>/users-count/', urs_views.api_workspace_users_count, name='api_workspace_users_count'),
    path('api/workspaces/<str:ws_id>/users-columns/', urs_views.api_workspace_users_columns, name='api_workspace_users_columns'),
    path('api/workspaces/<str:ws_id>/login-diag/', urs_views.api_workspace_login_diag, name='api_workspace_login_diag'),
    path('api/workspaces/<str:ws_id>/login-reset/', urs_views.api_workspace_login_reset, name='api_workspace_login_reset'),
    path('api/workspaces/<str:ws_id>/superuser/', urs_views.api_workspace_superuser, name='api_workspace_superuser'),
    path('enter/<str:ws_id>/', urs_views.workspace_login, name='workspace_login'),
    path('api/master/status/', urs_views.api_master_status, name='api_master_status'),
    path('api/master/auth/', urs_views.api_master_auth, name='api_master_auth'),
    path('api/workspaces/create/', urs_views.api_workspaces_create, name='api_workspaces_create'),
    path('api/lookup/lists/', urs_views.api_lookup_lists, name='api_lookup_lists'),
    path('api/lookup/tables/', urs_views.api_lookup_tables, name='api_lookup_tables'),
    path('api/workspaces/<str:ws_id>/save/', urs_views.api_workspace_save, name='api_workspace_save'),
    path('my-reports/', urs_views.my_reports, name='my_reports'),
    path('dashboards/', urs_views.dashboards, name='dashboards'),
    path('my-docs/', urs_views.my_docs, name='my_docs'),
    path('api/my-docs/list/', urs_views.api_my_docs_list, name='api_my_docs_list'),
    path('api/my-docs/save/', urs_views.api_my_docs_save, name='api_my_docs_save'),
    path('api/my-docs/delete/', urs_views.api_my_docs_delete, name='api_my_docs_delete'),
    path('api/my-docs/<str:doc_id>/thumb/', urs_views.api_my_docs_thumb, name='api_my_docs_thumb'),
    path('api/my-docs/<str:doc_id>/', urs_views.api_my_docs_view, name='api_my_docs_view'),
    # Players moved into urs/templates — keep sidebar navigation
    path('app/<str:app_name>/form/<str:fml_file>/', urs_views.app_form_player, name='app_form_player'),
    path('app/<str:app_name>/report/<str:rml_file>/', urs_views.app_report_player, name='app_report_player'),
    path('app/<str:app_name>/report-designer/', urs_views.app_report_designer, name='app_report_designer'),
    path('app/<str:app_name>/forms-designer/', urs_views.app_forms_designer, name='app_forms_designer'),
    path('app/<str:app_name>/data-diagram/', urs_views.app_data_diagram, name='app_data_diagram'),
    path('app/<str:app_name>/dml-designer/', urs_views.app_dml_designer, name='app_dml_designer'),
    path('app/<str:app_name>/', urs_views.app_detail, name='app_detail'),
    path('api/apps/', urs_views.api_apps, name='api_apps'),
    path('api/apps/create/', urs_views.api_apps_create, name='api_apps_create'),
    path('api/apps/icon/upload/', urs_views.api_apps_icon_upload, name='api_apps_icon_upload'),
    path('api/apps/<str:app_name>/icon-file', urs_views.api_apps_icon_file, name='api_apps_icon_file'),
    path('api/apps/<str:app_name>/files/', urs_views.api_app_files, name='api_app_files'),
    path('api/apps/<str:app_name>/rules/', urs_views.api_app_rules, name='api_app_rules'),
    path('api/apps/<str:app_name>/rules/policy/save/', urs_views.api_app_rule_policy_save, name='api_app_rule_policy_save'),
    path('api/apps/<str:app_name>/rules/policy/delete/', urs_views.api_app_rule_policy_delete, name='api_app_rule_policy_delete'),
    path('api/apps/sync/', urs_views.api_apps_sync, name='api_apps_sync'),
    path('api/apps/<str:app_name>/fml/create/', urs_views.api_create_fml, name='api_create_fml'),
    path('api/apps/<str:app_name>/rml/create/', urs_views.api_create_rml, name='api_create_rml'),
    path('api/apps/<str:app_name>/rml/update/', urs_views.api_update_rml, name='api_update_rml'),
    path('api/apps/<str:app_name>/dml/list/', urs_views.api_dml_list, name='api_dml_list'),
    path('api/apps/<str:app_name>/dml/suggest/', urs_views.api_dml_suggest, name='api_dml_suggest'),
    path('api/apps/<str:app_name>/dml/create/', urs_views.api_dml_create, name='api_dml_create'),
    path('api/apps/<str:app_name>/dml/update/', urs_views.api_dml_update, name='api_dml_update'),
    path('api/dml/metadata', urs_views.api_dml_metadata, name='api_dml_metadata'),
    path('api/dml/render', urs_views.api_dml_render, name='api_dml_render'),
    path('api/dml/xlsx', urs_views.api_dml_xlsx, name='api_dml_xlsx'),
    path('api/dml/pdf', urs_views.api_dml_pdf, name='api_dml_pdf'),
    path('api/dml/doc-pdf', urs_views.api_dml_doc_pdf, name='api_dml_doc_pdf'),
    path('api/connections/<int:conn_id>/tables/', urs_views.api_connection_tables, name='api_connection_tables'),
    path('api/connections/<int:conn_id>/tables/<str:table>/columns/', urs_views.api_connection_table_columns, name='api_connection_table_columns'),
    path('api/connections/<int:conn_id>/tables/<str:table>/preview/', urs_views.api_connection_table_preview, name='api_connection_table_preview'),
    path('api/connections/<int:conn_id>/tables/<str:table>/fks/', urs_views.api_connection_table_fks, name='api_connection_table_fks'),
    path('api/connections/<int:conn_id>/tables/<str:table>/rows/insert/', urs_views.api_json_row_insert, name='api_json_row_insert'),
    path('api/connections/<int:conn_id>/tables/<str:table>/rows/update/', urs_views.api_json_row_update, name='api_json_row_update'),
    path('api/connections/<int:conn_id>/tables/<str:table>/rows/delete/', urs_views.api_json_row_delete, name='api_json_row_delete'),
    path('api/formulas/', urs_views.api_formulas_list, name='api_formulas_list'),
    path('api/formulas/autocomplete/', urs_views.api_formulas_autocomplete, name='api_formulas_autocomplete'),
    path('api/formulas/migrate/', urs_views.api_formulas_migrate, name='api_formulas_migrate'),
    path('api/formulas/ddl/', urs_views.api_formulas_ddl, name='api_formulas_ddl'),
    path('api/custom-models/', urs_views.api_custom_models, name='api_custom_models'),
    path('api/custom-models/<str:name>/', urs_views.api_custom_model_detail, name='api_custom_model_detail'),
    path('api/custom-models/<str:name>/migrate/', urs_views.api_custom_model_migrate, name='api_custom_model_migrate'),
    path('api/connections/', urs_views.api_connections_list, name='api_connections_list'),
    path('api/connections/create/', urs_views.api_connection_create, name='api_connection_create'),
    path('api/connections/test/', urs_views.api_connection_test_record, name='api_connection_test_record'),
    path('api/connections/stats/', urs_views.api_connection_stats, name='api_connection_stats'),
    path('api/connections/<int:conn_id>/update/', urs_views.api_connection_update, name='api_connection_update'),
    path('api/connections/<int:conn_id>/delete/', urs_views.api_connection_delete, name='api_connection_delete'),
    path('api/connections/<int:conn_id>/test/', urs_views.api_connection_test, name='api_connection_test'),
    # IoT mirrors (UNION ALL + background sync → iot_<engine>_<endpoint> tables)
    path('api/iot/endpoints/', urs_views.api_iot_endpoints, name='api_iot_endpoints'),
    path('api/iot/fetch/', urs_views.api_iot_fetch, name='api_iot_fetch'),
    path('api/iot/mirror/', urs_views.api_iot_mirror, name='api_iot_mirror'),
    path('api/iot/mirrors/', urs_views.api_iot_mirrors, name='api_iot_mirrors'),
    path('api/iot/mirror/status/', urs_views.api_iot_mirror_status, name='api_iot_mirror_status'),
    path('api/iot/mirror/sync/', urs_views.api_iot_mirror_sync, name='api_iot_mirror_sync'),
    # CML Settings Engine (controls + business rules)
    path('settings/', urs_views.settings_home, name='settings_home'),
    path('settings/setup/', urs_views.settings_setup, name='settings_setup'),
    path('settings/<str:scope>/<str:app>/<str:file>/', urs_views.settings_detail, name='settings_detail'),
    path('api/setup/create/', urs_views.api_setup_create, name='api_setup_create'),
    path('api/setup/wizard/status/', urs_views.api_setup_wizard_status, name='api_setup_wizard_status'),
    path('api/setup/wizard/migrate/', urs_views.api_setup_wizard_migrate, name='api_setup_wizard_migrate'),
    path('api/setup/wizard/connection/', urs_views.api_setup_wizard_connection, name='api_setup_wizard_connection'),
    path('api/setup/wizard/connection/from-appconf/', urs_views.api_setup_wizard_connection_from_appconf, name='api_setup_wizard_connection_from_appconf'),
    path('api/setup/wizard/fmlk/', urs_views.api_setup_wizard_fmlk, name='api_setup_wizard_fmlk'),
    path('api/setup/wizard/retarget/', urs_views.api_setup_wizard_retarget, name='api_setup_wizard_retarget'),
    path('api/setup/wizard/seed/', urs_views.api_setup_wizard_seed, name='api_setup_wizard_seed'),
    path('api/settings/', urs_views.api_settings_list, name='api_settings_list'),
    path('api/cml/metadata', urs_views.api_cml_metadata, name='api_cml_metadata'),
    path('api/cml/validate/', urs_views.api_cml_validate, name='api_cml_validate'),
    path('api/cml/save/', urs_views.api_cml_save, name='api_cml_save'),
    path('api/cml/values', urs_views.api_cml_values, name='api_cml_values'),
    # FMLK API (proxied from fmlk_engine for same-host players)
    path('api/fmlk/metadata', urs_views.api_fmlk_metadata, name='api_fmlk_metadata'),
    path('api/fmlk/lookup', urs_views.api_fmlk_lookup, name='api_fmlk_lookup'),
    path('api/fmlk/options', urs_views.api_fmlk_options, name='api_fmlk_options'),
    path('api/fmlk/lookups', urs_views.api_fmlk_lookups, name='api_fmlk_lookups'),
    path('api/fmlk/display-map', urs_views.api_fmlk_display_map, name='api_fmlk_display_map'),
    path('api/fmlk/field-types', urs_views.api_fmlk_field_types, name='api_fmlk_field_types'),
    path('api/meta/categories', urs_views.api_meta_categories, name='api_meta_categories'),
    path('api/fmlk/preview_insert', urs_views.api_fmlk_preview_insert, name='api_fmlk_preview_insert'),
    path('api/fmlk/create', urs_views.api_fmlk_create, name='api_fmlk_create'),
    path('api/fmlk/update', urs_views.api_fmlk_update, name='api_fmlk_update'),
    path('api/fmlk/delete', urs_views.api_fmlk_delete, name='api_fmlk_delete'),
    path('api/fmlk/records', urs_views.api_fmlk_records, name='api_fmlk_records'),
    path('api/fmlk/calc-test', urs_views.api_fmlk_calc_test, name='api_fmlk_calc_test'),
    path('api/fmlk/serial-next', urs_views.api_fmlk_serial_next, name='api_fmlk_serial_next'),
    path('api/fmlk/record', urs_views.api_fmlk_record, name='api_fmlk_record'),
    path('api/fmlk/branch', urs_views.api_fmlk_branch, name='api_fmlk_branch'),
    path('api/fmlk/detail-search', urs_views.api_fmlk_detail_search, name='api_fmlk_detail_search'),
    path('api/fmlk/detail-sources', urs_views.api_fmlk_detail_sources, name='api_fmlk_detail_sources'),
    path('api/fmlk/master-branch', urs_views.api_fmlk_master_branch, name='api_fmlk_master_branch'),
    path('api/fmlk/action/test-connection', urs_views.api_fmlk_action_test_connection, name='api_fmlk_action_test_connection'),
    path('api/fmlk/branch/save', urs_views.api_fmlk_branch_save, name='api_fmlk_branch_save'),
    path('api/fmlk/sql-functions', urs_views.api_fmlk_sql_functions, name='api_fmlk_sql_functions'),
    path('api/fmlk/data-types', urs_views.api_fmlk_data_types, name='api_fmlk_data_types'),
    path('api/apps/<str:app_name>/models/design/', urs_views.api_models_design_save, name='api_models_design_save'),
    path('api/apps/<str:app_name>/models/migrate/', urs_views.api_models_migrate, name='api_models_migrate'),
    path('api/apps/<str:app_name>/models/migrate/preview/', urs_views.api_models_migrate_preview, name='api_models_migrate_preview'),
    path('api/apps/<str:app_name>/models/import-xlsx/', urs_views.api_fmlk_import_xlsx, name='api_fmlk_import_xlsx'),
    path('api/apps/<str:app_name>/models/convert-cml/', urs_views.api_models_convert_cml, name='api_models_convert_cml'),
    path('api/apps/<str:app_name>/models/sync/', urs_views.api_models_sync, name='api_models_sync'),
    path('api/apps/<str:app_name>/modals/<path:file>', urs_views.api_app_modal, name='api_app_modal'),
    # RML API (proxied from rml_python)
    path('api/rml/metadata', urs_views.api_rml_metadata, name='api_rml_metadata'),
    path('api/xsql/compile/', urs_views.api_xsql_compile, name='api_xsql_compile'),
    path('api/xsql/execute/', urs_views.api_xsql_execute, name='api_xsql_execute'),
    path('api/xsql/run/', urs_views.api_xsql_run, name='api_xsql_run'),
    path('api/xsql/from-rml/', urs_views.api_xsql_from_rml, name='api_xsql_from_rml'),
    path('api/rml/parse-sql/', urs_views.api_rml_parse_sql, name='api_rml_parse_sql'),
    path('api/rml/preview', urs_views.api_rml_preview, name='api_rml_preview'),
    path('api/rml/execute', urs_views.api_rml_execute, name='api_rml_execute'),
    path('api/rml/execute-async', urs_views.api_rml_execute_async, name='api_rml_execute_async'),
    path('api/rml/job/<str:job_id>', urs_views.api_rml_job, name='api_rml_job'),
    path('api/monitor/touch/', urs_views.api_monitor_touch, name='api_monitor_touch'),
    path('api/monitor/get/', urs_views.api_monitor_get, name='api_monitor_get'),
    path('api/apps/<str:app_name>/rml/draft/', urs_views.api_rml_draft, name='api_rml_draft'),
    path('api/apps/<str:app_name>/rml/draft/finalize/', urs_views.api_rml_draft_finalize, name='api_rml_draft_finalize'),
    path('api/apps/<str:app_name>/rml/draft/discard/', urs_views.api_rml_draft_discard, name='api_rml_draft_discard'),
    path('api/apps/<str:app_name>/rml/fetch-query/', urs_views.api_rml_fetch_query, name='api_rml_fetch_query'),
    path('api/apps/<str:app_name>/rml/design-preview/', urs_views.api_rml_design_preview, name='api_rml_design_preview'),
    path('api/rml/detail', urs_views.api_rml_detail, name='api_rml_detail'),
    path('api/rml/detail-search', urs_views.api_rml_detail_search, name='api_rml_detail_search'),
    path('api/rml/distinct', urs_views.api_rml_distinct, name='api_rml_distinct'),
    path('api/rml/groups', urs_views.api_rml_groups, name='api_rml_groups'),
    path('api/rml/joins', urs_views.api_rml_joins, name='api_rml_joins'),
    path('api/search/import-excel/', urs_views.api_search_import_excel, name='api_search_import_excel'),
    path('api/display-names/', urs_views.api_display_names, name='api_display_names'),
    path('api/display-names/save/', urs_views.api_display_names_save, name='api_display_names_save'),
    path('api/display-names/delete/', urs_views.api_display_names_delete, name='api_display_names_delete'),
    path('api/display-names/add-locale/', urs_views.api_display_names_add_locale, name='api_display_names_add_locale'),
    path('api/display-names/resolve/', urs_views.api_display_names_resolve, name='api_display_names_resolve'),
    path('api/presets/', urs_views.api_presets_list, name='api_presets_list'),
    path('api/presets/create/', urs_views.api_presets_create, name='api_presets_create'),
    path('api/presets/delete/', urs_views.api_presets_delete, name='api_presets_delete'),
]
